spring.application.name=backend
# Server Port Configuration
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/lms_db
spring.datasource.username=postgres

# JPA/Hibernate Configuration
# 'update' automatically updates the schema based on your entities. Good for development.

spring.jpa.hibernate.ddl-auto=create


# Shows the actual SQL queries in the console. Very useful for debugging.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Formats the SQL in the console to be more readable.
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=AndheNeMovieDekhiGungeNeGaanaGaaya #placeholder secret key
# 30 days in milliseconds
app.jwt.expiration-ms=2592000000

spring.profiles.active=local